marvel/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from marvel.models import User, db
from marvel.forms import UserLoginForm
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth', __name__, template_folder = 'auth_templates')
@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    userform = UserLoginForm()
    try:
        if request.method == 'POST' and userform.validate_on_submit():
            email = userform.email.data
            password = userform.password.data
            user = User(email = email, password = password)
            db.session.add(user)
            db.session.commit()
            flash(f'You have successfully created a user account {email}', 'user-created')
            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid Form Data: Please Check your form')
    return render_template('signup.html', form=userform)
@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    userform = UserLoginForm()
    try:
        if request.method == "POST" and userform.validate_on_submit():
            email = userform.email.data
            password = userform.password.data
            logged_user = User.query.filter_by(email = email).first()
            print(logged_user)
            print(check_password_hash(logged_user.password, password))
            print(logged_user.password)
            print(generate_password_hash(password))
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                print('You are successfully logged in via: Email/Password', 'auth.success')
                return redirect(url_for('site.profile'))
            else:
                print('Your Email/Password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
    
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('signin.html', form=userform)
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

marvel/site/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from marvel.forms import MarvelForm
from flask_login import login_required, current_user
from marvel.models import Marvel, MarvelSchema, db

site = Blueprint('site', __name__, template_folder='site_templates')
@site.route('/')
def home():
    return render_template('index.html')
    
@site.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    marvelform = MarvelForm()

    try:
        if request.method == 'POST' and marvelform.validate_on_submit():
            
            name = marvelform.name.data
            description = marvelform.description.data
            comics_appeared_in = marvelform.comics_appeared_in.data
            super_power = marvelform.super_power.data
            date_created = marvelform.date_created.data
            user_token = current_user.token
            marvel = Marvel(name, description, comics_appeared_in, super_power, date_created, user_token)
            db.session.add(marvel)
            db.session.commit()
            return redirect(url_for('site.profile')) 
    except:
        raise Exception('Character not created, please check your form and try again.')
    user_token = current_user.token
    marvels = Marvel.query.filter_by(user_token=user_token)
    return render_template('profile.html', form=marvelform, marvels=marvels)



   

marvel/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Marvel API</title>
</head>
<body>

    <nav class="ct-nav">
        <div>
            <img src="../static/images/newlogo.png" alt="Avengers Logo" id="marvel-nav-bar">
        </div>

        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>Avengers Homebase</li>
                </a>
                <a href="{{ url_for('site.home') }}">
                    <li>Home</li>
                </a>
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('site.profile')}}">
                        <li>Profile</li>
                    </a>
                    <a href="{{ url_for('auth.logout')}}">
                        <li>Log Out</li>
                    </a>
                {% else %}
                    <a href="{{ url_for('auth.signin') }}">
                        <li>Sign In</li>
                    </a>
                    <a href="{{ url_for('auth.signup') }}">
                        <li>Sign Up Free</li>
                    </a>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

marvel/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here...")}}
        </fieldset>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place Password Here...")}}
        </fieldset>

        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>

marvel/templates/marvelform.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
    <fieldset class="'name-field">
        {{ form.name.label }}
        {{ form.name(class='form-control', placeholder='Name') }}
    </fieldset>
    <fieldset class="'description-field">
        {{ form.description.label }}
        {{ form.description(class='form-control', placeholder='Description') }}
    </fieldset>
    <fieldset class="'comics-field">
        {{ form.comics_appeared_in.label }}
        {{ form.comics_appeared_in(class='form-control', placeholder='Comics') }}
    </fieldset>
    <fieldset class="'power-field">
        {{ form.super_power.label }}
        {{ form.super_power(class='form-control', placeholder='Power') }}
    </fieldset>
    <fieldset class="'date-field">
        {{ form.date_created.label }}
        {{ form.date_created(class='form-control', placeholder='Date') }}
    </fieldset>
    {{ form.submit_button(class='btn btn-primary btn-block mt-2')}}

</div>
</form>